version: "3.9"

networks:
  monit:


services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    networks:
      - monit
