version: "3.9"
services:
  app-catalogo-api:
    build:
      context: ./CatalogoCarros
      dockerfile: Dockerfile
      args:
        version: 1
    image: app-catalogo-api
    container_name: app-catalogo-api
    ports:
      - 8888:80
    networks:
      - catalogo-carros-network

  prometheus-catalogo-api:
    image: prom/prometheus
    container_name: prometheus-catalogo-api
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - catalogo-carros-network
    depends_on:
      - app-catalogo-api

  grafana-catalogo-api:
    image: grafana/grafana
    container_name: grafana-catalogo-api
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - catalogo-carros-network
    depends_on:
      - prometheus-catalogo-api

  client-catalogo-api:
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: client-catalogo-api
    container_name: client-catalogo-api
    restart: unless-stopped
    networks:
      - catalogo-carros-network
    depends_on:
      - grafana-catalogo-api

networks:
  catalogo-carros-network:
    driver: bridge
