apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "catalogo-carro-job"
        metrics_path: /metrics
        static_configs:
          - targets:
              - catalogo-carros-service:80
